import '../styles/globals.css'
import Nav from '../components/Nav'
import { CountriesProvider } from '../context'
import RandomCountry from '../components/randomCountry'
import Head from 'next/head';
function MyApp({ Component, pageProps }) {
  return (
    <CountriesProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

        </Head>
        <Nav/>
        <RandomCountry />
       <Component {...pageProps} />
    </CountriesProvider>
   
  )
}

export default MyApp
