import '../styles/globals.css'
import Nav from '../components/Nav'
import { CountriesProvider } from '../context'
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <CountriesProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        </Head>
        <Nav/>
       
       <Component {...pageProps} />
    </CountriesProvider>
   
  )
}

export default MyApp
